services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nfl-stats-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - APP_PORT=8080
      - APP_SECRET=your-secret-key-here
      - LOG_LEVEL=debug
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=sportsdata_nfl
      - MONGO_TIMEOUT=10
      - SPORTSDATA_API_KEY=${SPORTSDATA_API_KEY}
      - SPORTSDATA_API_BASE_URL=https://api.sportsdata.io/v3/nfl
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: nfl-stats-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=sportsdata_nfl

volumes:
  mongodb_data: